// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:698271d2-86da-438f-bf98-835096921598",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_hWN4ipDvy",
    "aws_user_pools_web_client_id": "73mpovdig0gc9v11lchjonjmil",
    "oauth": {}
};


export default awsmobile;
